#!/usr/bin/env ruby
#
# Script that finds and kill runaway EMR jobs
#
# Copyright(c) 2011 by Appcelerator, Inc. All Rights Reserved.
# This is proprietary software. Do not redistribute without express
# written permission.
#
# Initial Author: Maxim Negadaylov, 10/20/11
# Latest Modification: Ronen Botzer, 12/19/11
#
require 'rubygems'
require 'optparse'
require 'sqlite3'

File.delete("../dbs/test2.db") if File.exist?("../dbs/test2.db")
db = SQLite3::Database.new("/tmp/ramdisk/test2.db")

sql = <<SQL
create table categories (
    id INTEGER NOT NULL PRIMARY KEY,
    category_name text,
    description text
);

create table packages (
    id INTEGER NOT NULL PRIMARY KEY,
    category_id INTEGER NOT NULL,
    package_name text,
    description text,
    homepage text,
    licence INTEGER
);
SQL
    #licence INTEGER NOT NULL

db.execute_batch(sql)

portage_home = "/tmp/ramdisk/portage/"
a = []
start = Time.now
Dir.new(portage_home).sort.each  { |x|
    next if x == '.'
    next if x == '..'
    next if File.file?(portage_home + x)
    if x.index('-') == nil
        a.push(x)
        puts "skipping #(x)"
        next
    end

    db.execute("INSERT INTO categories (category_name) VALUES ('#{x}');")
    last_id = db.execute("SELECT last_insert_rowid();").flatten[0]

    Dir.new(portage_home + x).sort.each  { |xz|
        next if File.file?(xz)
        db.execute("INSERT INTO packages (category_id, package_name) VALUES (#{last_id}, '#{xz}');")
        puts "finished processing of `#{xz}`"
        puts "-"*20 
    }

    puts "finished processing of `#{x}`" 
    puts "="*20 
}
finish = Time.now

puts start
puts finish

p db.execute("SELECT * FROM packages where category_id=153;")
