#!/usr/bin/env ruby
require 'optparse'
require 'fileutils'
require 'time'

options = {
    :download_snapshot => false,
    :home_folder => 'portage3_data',
    :download_url => 'http://de-mirror.org/gentoo/snapshots/portage-latest.tar.bz2',
    :portage_home => 'portage',
    :recreate_tree => false,
    :required_space => 700,
    :snapshots_home => '../snapshots/',
    :snapshot_name => 'portage-latest.tar.bz2',
    :storage => '/dev/shm',
}

OptionParser.new do |opts|
    # help header
    opts.banner = " Usage: purge_s3_data [options]\n"
    opts.separator " A script that purges outdated data from s3 bucket\n"

    opts.on("-d", "--download-snapshot", "Redownload latest snapshot") do |value|
        options[:download_snapshot] = true
        options[:recreate_tree] = true
    end

    opts.on("-r", "--recreate-tree", "Recreate portage tree") do |value|
        options[:recreate_tree] = true
    end

    opts.on("-u", "--url STRING", "URL where snapshot is located") do |value|
        options[:download_url] = value
    end

    # parsing 'quite' option if present
    opts.on("-q", "--quiet", "Quiet mode") do |value|
        options[:quiet] = true
    end

    # parsing 'help' option if present
    opts.on_tail("-h", "--help", "Show this message") do
        puts opts
        exit
    end
end.parse!

print "Checking if '#{options[:storage]}' is a symlink on target system.. "
if File.symlink?(options[:storage])
    options[:storage] = File.readlink(options[:storage])
    puts "YES"
else
    puts "NO"
end

print "Checking if '#{options[:storage]}' path is  present on target system.. "
if File.exist?(options[:storage])
    puts "OK"
else
    puts "ERROR: '#{options[:storage]}' location can not be found on target system"
    exit(1)
end

print "Checking if '#{options[:storage]}' is a directory on target system.. "
if File.directory?(options[:storage])
    puts "OK"
else
    puts "ERROR: '#{options[:storage]}' is not a directory on target system"
    exit(1)
end

print "Checking if '#{options[:storage]}' is writable on target system.. "
if File.writable?(options[:storage])
    puts "OK"
else
    puts "ERROR: '#{options[:storage]}' is not writable on target system"
    exit(1)
end

print "Checking if '#{options[:storage]}' has enough free space on target system.. "
space_available = `df -kP #{options[:storage]}`.split("\n")[1].split(" ")[3].to_i
if space_available > options[:required_space] * 1024
    puts "OK"
else
    puts "ERROR: '#{options[:storage]}' does not have enough free space"
    exit(1)
end

if options[:download_snapshot]
    puts "Starting download latest portage snapshot.."
    file_location = File.join(
        options[:snapshots_home],
        options[:snapshot_name]
    )

    if file_location.index('latest') != nil
        file_location.gsub!("latest", Time.now.strftime("%Y%m%d-%H%M%S"))
    end

    `wget -O #{file_location} #{options[:download_url]}`
end

home_path = File.join(options[:storage], options[:home_folder])
full_path = File.join(home_path, options[:portage_home])

if options[:recreate_tree] || !File.exist?(home_path) || !File.exist?(full_path)
    FileUtils.rm_r(full_path) if File.exist?(full_path)
    Dir.mkdir(home_path) if !File.exist?(home_path)
    print "Sarting to exctact portage snapshots.. "
    `tar xjf #{file_location} -C #{full_path}`
    puts "Done"
end

